### ISSUE TITLE
Brief feedback

### ISSUE THREAD

**Issue by PoppyRed91** [Cyloon/heavenlycloud#1]
I see you put script for js in the beginning of the body. It is not a bad practice but better one is to put it on the end of the body also, if you have more than a few lines of code, put the code in another file like script.js and then reference it on the end of the body.

Further, using var for variables is really deprecated, let or const are better choice and please look into naming convenctions of variables and functions! :)

Why does your first div have 2 classes (site-container AND MouseTrail)? 

Check your hierarchy. Where does your second div (with class site-main-container) ends?

<br> is only basically used to put text in another row, not really to make a space between images. You can do that with grid or flexbox by setting a display property.

In style.css, 5th line of code: What is a figure? Also, why ol? You don't have an unordered list in your html.¨

Maybe just a tip regarding adding padding or margin bottom, it could be easier to just add margin top on every element and it's child since code is running top to bottom.

Why do you have 2 button:hover? button:hover and then button:hover a - what is this a?

Can you please send me a link of your website? Thanks! :D

**Comment by Cyloon** [comment]
Thanks for the feedback!
I borrowed all the javascript so I have no idea!
I'll check out the other tips.
The "button:hover a" is targeting the anchor tag "a" because it's a link.

**Comment by PoppyRed91** [comment]
Okay, I see! It works! Just wouldn't hurt updating it, just so it looks like modern javascript. 
Aaah I see now the link, sorry, I missed it!


Hope something will help :D Good luck! :D
